language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - pip install --upgrade pip
 - pip install sympy
 - pip install --upgrade sympy
 - pip install -r requirements.txt
 - pip install -e .